### ISSUE TITLE
FSTAB: nobootwait option

### ISSUE THREAD

**Issue by Have-Purple** [trapexit/backup-and-recovery-howtos#1]
Using nobootwait in debian Jessie fails.  Removing it and everything works great.

PS.  I'm github noob.  No idea if this is how I'm supposed to report issues.

**Comment by trapexit** [comment]
What document are you referring to? The guides are generic. I can't speak to Debian Jessie's support but it works in other distros. As the /etc/fstab document implies it's an optional value.

**Comment by Have-Purple** [comment]
Fair enough.

**Comment by ben-ba** [comment]
nofail is an equivalent option.

**Comment by Gerben-Tx** [comment]
(for future readers)

> nofail is an equivalent option.

To be precise; `nofail,x-systemd.device-timeout=1` is equivalent to `nobootwait` according to https://askubuntu.com/questions/786928/ubuntu-16-04-fstab-fails-with-nobootwait

`nobootwait` seems to have been removed from Ubuntu 16.04
